# Generated by Django 5.2.15 on 2026-06-25 18:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique alphanumeric code entered by the user.', max_length=50, unique=True)),
                ('discount_percent', models.IntegerField(help_text='Percentage discount value from 1 to 100.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_usages', models.PositiveIntegerField(help_text='Global maximum number of times this promo code can be used.')),
                ('current_usages', models.PositiveIntegerField(default=0, help_text='Tracks how many times this promo code has been successfully applied.')),
                ('valid_until', models.DateTimeField(help_text='The expiration date and time of the promotional campaign.')),
                ('allowed_categories', models.JSONField(blank=True, default=list, help_text='List of product category slugs this promo applies to. If empty, applies to all.')),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
            },
        ),
        migrations.CreateModel(
            name='UserPromoUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_usages', to='promotions.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_promos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Promo Usage',
                'verbose_name_plural': 'User Promo Usages',
                'unique_together': {('user', 'promocode')},
            },
        ),
    ]
